Table users {
  id integer
  username varchar
  password varchar
}

Table user_results {
  user_id integer
  quiz_id integer
  high_score numeric
}

Table quiz_topic {
  topic_id integer
  name varchar
}

Table quiz {
  topic_id integer
  quiz_id integer
  question varchar
}

Table quiz_answers {
  quiz_id integer
  answer varchar
  correct boolean
}



Ref: users.id > user_results.user_id
Ref: quiz.quiz_id > user_results.quiz_id
Ref: quiz.quiz_id > quiz_answers.quiz_id
Ref: quiz_topic.topic_id > quiz.topic_id